# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {DRC REQP-1839}  -suppress 
set_msg_config  -ruleid {10}  -id {DRC DPREG-4}  -suppress 
set_msg_config  -ruleid {11}  -id {DRC RTSTAT-10}  -suppress 
set_msg_config  -ruleid {12}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {13}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {14}  -id {Synth 8-295}  -new_severity {WARNING} 
set_msg_config  -ruleid {15}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {16}  -id {Synth 8-3295}  -new_severity {INFO} 
set_msg_config  -ruleid {17}  -id {Synth 8-3848}  -new_severity {CRITICAL WARNING} 
set_msg_config  -ruleid {18}  -id {Synth 8-3352}  -new_severity {ERROR} 
set_msg_config  -ruleid {2}  -id {Common 17-1355}  -suppress 
set_msg_config  -ruleid {3}  -id {DRC CHECK-3}  -suppress 
set_msg_config  -ruleid {4}  -id {DRC DPIP-1}  -suppress 
set_msg_config  -ruleid {5}  -id {DRC REQP-1840}  -suppress 
set_msg_config  -ruleid {6}  -id {Synth 8-3332}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {Synth 8-3331}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {DRC DPOP-1}  -suppress 
set_msg_config  -ruleid {9}  -id {DRC DPOP-2}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7a200tfbg484-2
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.cache/wt [current_project]
  set_property parent.project_path /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.xpr [current_project]
  set_property ip_output_repo /media/sf_temp/dsn_s3100_sv_pgu_git/txem7310_pll/txem7310_pll.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.runs/synth_1/txem7310_pll__s3100_sv_adda__top.dcp
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/fifo_generator_3_2/fifo_generator_3_2.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/fifo_generator_3_1/fifo_generator_3_1.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/microblaze_mcs_1/microblaze_mcs_1.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/clk_wiz_0_3_1/clk_wiz_0_3_1.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/clk_wiz_0_0_1/clk_wiz_0_0_1.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/clk_wiz_2_2/clk_wiz_2_2.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/clk_wiz_1_2/clk_wiz_1_2.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/fifo_generator_5_1_2/fifo_generator_5_1_2.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/clk_wiz_0_2_3/clk_wiz_0_2_3.xci
  read_ip -quiet /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
  read_xdc /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/constrs_1/new/debug_net.xdc
  read_xdc /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/constrs_1/new/debug_cores.xdc
  read_xdc /media/sf_temp/dsn_adda_s3100_git/txem7310_pll/txem7310_pll.srcs/constrs_1/imports/src_ref/txem7310_pll__s3100_sv_adda__top.xdc
  link_design -top txem7310_pll__s3100_sv_adda__top -part xc7a200tfbg484-2
  write_hwdef -force -file txem7310_pll__s3100_sv_adda__top.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design -directive Explore
  write_checkpoint -force txem7310_pll__s3100_sv_adda__top_opt.dcp
  create_report "impl_1_2_opt_report_drc_0" "report_drc -file txem7310_pll__s3100_sv_adda__top_drc_opted.rpt -pb txem7310_pll__s3100_sv_adda__top_drc_opted.pb -rpx txem7310_pll__s3100_sv_adda__top_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  implement_debug_core 
  place_design -directive Explore
  write_checkpoint -force txem7310_pll__s3100_sv_adda__top_placed.dcp
  create_report "impl_1_2_place_report_io_0" "report_io -file txem7310_pll__s3100_sv_adda__top_io_placed.rpt"
  create_report "impl_1_2_place_report_utilization_0" "report_utilization -file txem7310_pll__s3100_sv_adda__top_utilization_placed.rpt -pb txem7310_pll__s3100_sv_adda__top_utilization_placed.pb"
  create_report "impl_1_2_place_report_control_sets_0" "report_control_sets -verbose -file txem7310_pll__s3100_sv_adda__top_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design -directive Explore
  write_checkpoint -force txem7310_pll__s3100_sv_adda__top_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force txem7310_pll__s3100_sv_adda__top_routed.dcp
  create_report "impl_1_2_route_report_drc_0" "report_drc -file txem7310_pll__s3100_sv_adda__top_drc_routed.rpt -pb txem7310_pll__s3100_sv_adda__top_drc_routed.pb -rpx txem7310_pll__s3100_sv_adda__top_drc_routed.rpx"
  create_report "impl_1_2_route_report_methodology_0" "report_methodology -file txem7310_pll__s3100_sv_adda__top_methodology_drc_routed.rpt -pb txem7310_pll__s3100_sv_adda__top_methodology_drc_routed.pb -rpx txem7310_pll__s3100_sv_adda__top_methodology_drc_routed.rpx"
  create_report "impl_1_2_route_report_power_0" "report_power -file txem7310_pll__s3100_sv_adda__top_power_routed.rpt -pb txem7310_pll__s3100_sv_adda__top_power_summary_routed.pb -rpx txem7310_pll__s3100_sv_adda__top_power_routed.rpx"
  create_report "impl_1_2_route_report_route_status_0" "report_route_status -file txem7310_pll__s3100_sv_adda__top_route_status.rpt -pb txem7310_pll__s3100_sv_adda__top_route_status.pb"
  create_report "impl_1_2_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file txem7310_pll__s3100_sv_adda__top_timing_summary_routed.rpt -rpx txem7310_pll__s3100_sv_adda__top_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_2_route_report_incremental_reuse_0" "report_incremental_reuse -file txem7310_pll__s3100_sv_adda__top_incremental_reuse_routed.rpt"
  create_report "impl_1_2_route_report_clock_utilization_0" "report_clock_utilization -file txem7310_pll__s3100_sv_adda__top_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force txem7310_pll__s3100_sv_adda__top_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force txem7310_pll__s3100_sv_adda__top.mmi }
  catch { write_bmm -force txem7310_pll__s3100_sv_adda__top_bd.bmm }
  write_bitstream -force txem7310_pll__s3100_sv_adda__top.bit 
  catch { write_sysdef -hwdef txem7310_pll__s3100_sv_adda__top.hwdef -bitfile txem7310_pll__s3100_sv_adda__top.bit -meminfo txem7310_pll__s3100_sv_adda__top.mmi -file txem7310_pll__s3100_sv_adda__top.sysdef }
  catch {write_debug_probes -quiet -force txem7310_pll__s3100_sv_adda__top}
  catch {file copy -force txem7310_pll__s3100_sv_adda__top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

