create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_1_2_0_inst/inst/clk_out1_200M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {DAC0_DAT[0]} {DAC0_DAT[1]} {DAC0_DAT[2]} {DAC0_DAT[3]} {DAC0_DAT[4]} {DAC0_DAT[5]} {DAC0_DAT[6]} {DAC0_DAT[7]} {DAC0_DAT[8]} {DAC0_DAT[9]} {DAC0_DAT[10]} {DAC0_DAT[11]} {DAC0_DAT[12]} {DAC0_DAT[13]} {DAC0_DAT[14]} {DAC0_DAT[15]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_1_2_1_inst/inst/clk_out3_200M_180]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {DAC1_DAT[0]} {DAC1_DAT[1]} {DAC1_DAT[2]} {DAC1_DAT[3]} {DAC1_DAT[4]} {DAC1_DAT[5]} {DAC1_DAT[6]} {DAC1_DAT[7]} {DAC1_DAT[8]} {DAC1_DAT[9]} {DAC1_DAT[10]} {DAC1_DAT[11]} {DAC1_DAT[12]} {DAC1_DAT[13]} {DAC1_DAT[14]} {DAC1_DAT[15]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list clk_wiz_0_3_1_inst/inst/clk_out1_72M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 32 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {adc_wrapper__inst/i_HSADC_SMP_PRD[0]} {adc_wrapper__inst/i_HSADC_SMP_PRD[1]} {adc_wrapper__inst/i_HSADC_SMP_PRD[2]} {adc_wrapper__inst/i_HSADC_SMP_PRD[3]} {adc_wrapper__inst/i_HSADC_SMP_PRD[4]} {adc_wrapper__inst/i_HSADC_SMP_PRD[5]} {adc_wrapper__inst/i_HSADC_SMP_PRD[6]} {adc_wrapper__inst/i_HSADC_SMP_PRD[7]} {adc_wrapper__inst/i_HSADC_SMP_PRD[8]} {adc_wrapper__inst/i_HSADC_SMP_PRD[9]} {adc_wrapper__inst/i_HSADC_SMP_PRD[10]} {adc_wrapper__inst/i_HSADC_SMP_PRD[11]} {adc_wrapper__inst/i_HSADC_SMP_PRD[12]} {adc_wrapper__inst/i_HSADC_SMP_PRD[13]} {adc_wrapper__inst/i_HSADC_SMP_PRD[14]} {adc_wrapper__inst/i_HSADC_SMP_PRD[15]} {adc_wrapper__inst/i_HSADC_SMP_PRD[16]} {adc_wrapper__inst/i_HSADC_SMP_PRD[17]} {adc_wrapper__inst/i_HSADC_SMP_PRD[18]} {adc_wrapper__inst/i_HSADC_SMP_PRD[19]} {adc_wrapper__inst/i_HSADC_SMP_PRD[20]} {adc_wrapper__inst/i_HSADC_SMP_PRD[21]} {adc_wrapper__inst/i_HSADC_SMP_PRD[22]} {adc_wrapper__inst/i_HSADC_SMP_PRD[23]} {adc_wrapper__inst/i_HSADC_SMP_PRD[24]} {adc_wrapper__inst/i_HSADC_SMP_PRD[25]} {adc_wrapper__inst/i_HSADC_SMP_PRD[26]} {adc_wrapper__inst/i_HSADC_SMP_PRD[27]} {adc_wrapper__inst/i_HSADC_SMP_PRD[28]} {adc_wrapper__inst/i_HSADC_SMP_PRD[29]} {adc_wrapper__inst/i_HSADC_SMP_PRD[30]} {adc_wrapper__inst/i_HSADC_SMP_PRD[31]}]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list clk_wiz_0_2_3_inst/inst/clk_out3_63M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 18 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list {adc_wrapper__inst/o_hsadc_fifo_adc0_din[0]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[1]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[2]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[3]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[4]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[5]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[6]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[7]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[8]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[9]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[10]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[11]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[12]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[13]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[14]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[15]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[16]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[17]}]]
create_debug_core u_ila_4 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_4]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_4]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_4]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_4]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_4]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_4]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_4]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_4]
set_property port_width 1 [get_debug_ports u_ila_4/clk]
connect_debug_port u_ila_4/clk [get_nets [list clk_wiz_0_0_1_inst/inst/clk_out1_10M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe0]
set_property port_width 1 [get_debug_ports u_ila_4/probe0]
connect_debug_port u_ila_4/probe0 [get_nets [list adc_wrapper__inst/i_hsadc_fifo_rst]]
create_debug_core u_ila_5 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_5]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_5]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_5]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_5]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_5]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_5]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_5]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_5]
set_property port_width 1 [get_debug_ports u_ila_5/clk]
connect_debug_port u_ila_5/clk [get_nets [list clk_wiz_2_2_inst/inst/clk_out1_104M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe0]
set_property port_width 1 [get_debug_ports u_ila_5/probe0]
connect_debug_port u_ila_5/probe0 [get_nets [list slave_spi_mth_brd__M2_inst/i_SPI_CLK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fcid_pulse_active_dac0]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fcid_pulse_active_dac1]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 18 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[0]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[1]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[2]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[3]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[4]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[5]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[6]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[7]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[8]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[9]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[10]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[11]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[12]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[13]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[14]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[15]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[16]} {adc_wrapper__inst/o_hsadc_fifo_adc1_dout[17]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 18 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[0]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[1]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[2]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[3]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[4]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[5]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[6]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[7]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[8]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[9]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[10]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[11]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[12]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[13]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[14]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[15]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[16]} {adc_wrapper__inst/o_hsadc_fifo_adc0_dout[17]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 32 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {adc_wrapper__inst/i_HSADC_UPD_SMP[0]} {adc_wrapper__inst/i_HSADC_UPD_SMP[1]} {adc_wrapper__inst/i_HSADC_UPD_SMP[2]} {adc_wrapper__inst/i_HSADC_UPD_SMP[3]} {adc_wrapper__inst/i_HSADC_UPD_SMP[4]} {adc_wrapper__inst/i_HSADC_UPD_SMP[5]} {adc_wrapper__inst/i_HSADC_UPD_SMP[6]} {adc_wrapper__inst/i_HSADC_UPD_SMP[7]} {adc_wrapper__inst/i_HSADC_UPD_SMP[8]} {adc_wrapper__inst/i_HSADC_UPD_SMP[9]} {adc_wrapper__inst/i_HSADC_UPD_SMP[10]} {adc_wrapper__inst/i_HSADC_UPD_SMP[11]} {adc_wrapper__inst/i_HSADC_UPD_SMP[12]} {adc_wrapper__inst/i_HSADC_UPD_SMP[13]} {adc_wrapper__inst/i_HSADC_UPD_SMP[14]} {adc_wrapper__inst/i_HSADC_UPD_SMP[15]} {adc_wrapper__inst/i_HSADC_UPD_SMP[16]} {adc_wrapper__inst/i_HSADC_UPD_SMP[17]} {adc_wrapper__inst/i_HSADC_UPD_SMP[18]} {adc_wrapper__inst/i_HSADC_UPD_SMP[19]} {adc_wrapper__inst/i_HSADC_UPD_SMP[20]} {adc_wrapper__inst/i_HSADC_UPD_SMP[21]} {adc_wrapper__inst/i_HSADC_UPD_SMP[22]} {adc_wrapper__inst/i_HSADC_UPD_SMP[23]} {adc_wrapper__inst/i_HSADC_UPD_SMP[24]} {adc_wrapper__inst/i_HSADC_UPD_SMP[25]} {adc_wrapper__inst/i_HSADC_UPD_SMP[26]} {adc_wrapper__inst/i_HSADC_UPD_SMP[27]} {adc_wrapper__inst/i_HSADC_UPD_SMP[28]} {adc_wrapper__inst/i_HSADC_UPD_SMP[29]} {adc_wrapper__inst/i_HSADC_UPD_SMP[30]} {adc_wrapper__inst/i_HSADC_UPD_SMP[31]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list adc_wrapper__inst/i_hsadc_fifo_adc0_rd_en]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list adc_wrapper__inst/i_hsadc_fifo_adc1_rd_en]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list w_mcs_ep_wi_en]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
set_property port_width 18 [get_debug_ports u_ila_3/probe1]
connect_debug_port u_ila_3/probe1 [get_nets [list {adc_wrapper__inst/o_hsadc_fifo_adc1_din[0]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[1]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[2]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[3]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[4]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[5]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[6]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[7]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[8]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[9]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[10]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[11]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[12]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[13]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[14]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[15]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[16]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[17]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe2]
set_property port_width 1 [get_debug_ports u_ila_3/probe2]
connect_debug_port u_ila_3/probe2 [get_nets [list adc_wrapper__inst/o_hsadc_fifo_adc0_wr_ack]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe3]
set_property port_width 1 [get_debug_ports u_ila_3/probe3]
connect_debug_port u_ila_3/probe3 [get_nets [list adc_wrapper__inst/o_hsadc_fifo_adc1_wr_ack]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe1]
set_property port_width 1 [get_debug_ports u_ila_4/probe1]
connect_debug_port u_ila_4/probe1 [get_nets [list adc_wrapper__inst/i_hsadc_init]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe2]
set_property port_width 1 [get_debug_ports u_ila_4/probe2]
connect_debug_port u_ila_4/probe2 [get_nets [list adc_wrapper__inst/i_hsadc_reset]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe3]
set_property port_width 1 [get_debug_ports u_ila_4/probe3]
connect_debug_port u_ila_4/probe3 [get_nets [list adc_wrapper__inst/i_hsadc_update]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe4]
set_property port_width 1 [get_debug_ports u_ila_4/probe4]
connect_debug_port u_ila_4/probe4 [get_nets [list adc_wrapper__inst/o_hsadc_init_done]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe5]
set_property port_width 1 [get_debug_ports u_ila_4/probe5]
connect_debug_port u_ila_4/probe5 [get_nets [list adc_wrapper__inst/o_hsadc_update_done]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe1]
set_property port_width 1 [get_debug_ports u_ila_5/probe1]
connect_debug_port u_ila_5/probe1 [get_nets [list slave_spi_mth_brd__M2_inst/i_SPI_CS_B]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe2]
set_property port_width 1 [get_debug_ports u_ila_5/probe2]
connect_debug_port u_ila_5/probe2 [get_nets [list slave_spi_mth_brd__M2_inst/i_SPI_MOSI]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe3]
set_property port_width 1 [get_debug_ports u_ila_5/probe3]
connect_debug_port u_ila_5/probe3 [get_nets [list slave_spi_mth_brd__M2_inst/o_SPI_MISO]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe4]
set_property port_width 1 [get_debug_ports u_ila_5/probe4]
connect_debug_port u_ila_5/probe4 [get_nets [list slave_spi_mth_brd__M2_inst/o_SPI_MISO_EN]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe5]
set_property port_width 1 [get_debug_ports u_ila_5/probe5]
connect_debug_port u_ila_5/probe5 [get_nets [list w_mcs_ep_disable]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe6]
set_property port_width 1 [get_debug_ports u_ila_5/probe6]
connect_debug_port u_ila_5/probe6 [get_nets [list w_SSPI_TEST_mode_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets base_sspi_clk]
