create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_1_2_0_inst/inst/clk_out1_200M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {DAC0_DAT[0]} {DAC0_DAT[1]} {DAC0_DAT[2]} {DAC0_DAT[3]} {DAC0_DAT[4]} {DAC0_DAT[5]} {DAC0_DAT[6]} {DAC0_DAT[7]} {DAC0_DAT[8]} {DAC0_DAT[9]} {DAC0_DAT[10]} {DAC0_DAT[11]} {DAC0_DAT[12]} {DAC0_DAT[13]} {DAC0_DAT[14]} {DAC0_DAT[15]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_1_2_1_inst/inst/clk_out3_200M_180]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {DAC1_DAT[0]} {DAC1_DAT[1]} {DAC1_DAT[2]} {DAC1_DAT[3]} {DAC1_DAT[4]} {DAC1_DAT[5]} {DAC1_DAT[6]} {DAC1_DAT[7]} {DAC1_DAT[8]} {DAC1_DAT[9]} {DAC1_DAT[10]} {DAC1_DAT[11]} {DAC1_DAT[12]} {DAC1_DAT[13]} {DAC1_DAT[14]} {DAC1_DAT[15]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list clk_wiz_0_3_1_inst/inst/clk_out1_72M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 32 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {lan_endpoint_wrapper_inst/ep93pipe[0]} {lan_endpoint_wrapper_inst/ep93pipe[1]} {lan_endpoint_wrapper_inst/ep93pipe[2]} {lan_endpoint_wrapper_inst/ep93pipe[3]} {lan_endpoint_wrapper_inst/ep93pipe[4]} {lan_endpoint_wrapper_inst/ep93pipe[5]} {lan_endpoint_wrapper_inst/ep93pipe[6]} {lan_endpoint_wrapper_inst/ep93pipe[7]} {lan_endpoint_wrapper_inst/ep93pipe[8]} {lan_endpoint_wrapper_inst/ep93pipe[9]} {lan_endpoint_wrapper_inst/ep93pipe[10]} {lan_endpoint_wrapper_inst/ep93pipe[11]} {lan_endpoint_wrapper_inst/ep93pipe[12]} {lan_endpoint_wrapper_inst/ep93pipe[13]} {lan_endpoint_wrapper_inst/ep93pipe[14]} {lan_endpoint_wrapper_inst/ep93pipe[15]} {lan_endpoint_wrapper_inst/ep93pipe[16]} {lan_endpoint_wrapper_inst/ep93pipe[17]} {lan_endpoint_wrapper_inst/ep93pipe[18]} {lan_endpoint_wrapper_inst/ep93pipe[19]} {lan_endpoint_wrapper_inst/ep93pipe[20]} {lan_endpoint_wrapper_inst/ep93pipe[21]} {lan_endpoint_wrapper_inst/ep93pipe[22]} {lan_endpoint_wrapper_inst/ep93pipe[23]} {lan_endpoint_wrapper_inst/ep93pipe[24]} {lan_endpoint_wrapper_inst/ep93pipe[25]} {lan_endpoint_wrapper_inst/ep93pipe[26]} {lan_endpoint_wrapper_inst/ep93pipe[27]} {lan_endpoint_wrapper_inst/ep93pipe[28]} {lan_endpoint_wrapper_inst/ep93pipe[29]} {lan_endpoint_wrapper_inst/ep93pipe[30]} {lan_endpoint_wrapper_inst/ep93pipe[31]}]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list clk_wiz_0_2_3_inst/inst/clk_out1_189M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 2 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list {adc_wrapper__inst/control_hsadc_dual__inst/serdes[1].serdes_ddr_2lane_in_20bit_out_inst/i_data_s[0]} {adc_wrapper__inst/control_hsadc_dual__inst/serdes[1].serdes_ddr_2lane_in_20bit_out_inst/i_data_s[1]}]]
create_debug_core u_ila_4 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_4]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_4]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_4]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_4]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_4]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_4]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_4]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_4]
set_property port_width 1 [get_debug_ports u_ila_4/clk]
connect_debug_port u_ila_4/clk [get_nets [list clk_wiz_2_2_inst/inst/clk_out1_104M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe0]
set_property port_width 10 [get_debug_ports u_ila_4/probe0]
connect_debug_port u_ila_4/probe0 [get_nets [list {slave_spi_mth_brd__M2_inst/r_frame_adrs[0]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[1]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[2]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[3]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[4]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[5]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[6]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[7]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[8]} {slave_spi_mth_brd__M2_inst/r_frame_adrs[9]}]]
create_debug_core u_ila_5 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_5]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_5]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_5]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_5]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_5]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_5]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_5]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_5]
set_property port_width 1 [get_debug_ports u_ila_5/clk]
connect_debug_port u_ila_5/clk [get_nets [list clk_wiz_0_2_3_inst/inst/clk_out3_60M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe0]
set_property port_width 18 [get_debug_ports u_ila_5/probe0]
connect_debug_port u_ila_5/probe0 [get_nets [list {adc_wrapper__inst/o_hsadc_fifo_adc0_din[0]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[1]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[2]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[3]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[4]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[5]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[6]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[7]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[8]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[9]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[10]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[11]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[12]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[13]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[14]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[15]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[16]} {adc_wrapper__inst/o_hsadc_fifo_adc0_din[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {w_dac0_data_pin[0]} {w_dac0_data_pin[1]} {w_dac0_data_pin[2]} {w_dac0_data_pin[3]} {w_dac0_data_pin[4]} {w_dac0_data_pin[5]} {w_dac0_data_pin[6]} {w_dac0_data_pin[7]} {w_dac0_data_pin[8]} {w_dac0_data_pin[9]} {w_dac0_data_pin[10]} {w_dac0_data_pin[11]} {w_dac0_data_pin[12]} {w_dac0_data_pin[13]} {w_dac0_data_pin[14]} {w_dac0_data_pin[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fcid_pulse_active_dac0]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 16 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {w_dac1_data_pin[0]} {w_dac1_data_pin[1]} {w_dac1_data_pin[2]} {w_dac1_data_pin[3]} {w_dac1_data_pin[4]} {w_dac1_data_pin[5]} {w_dac1_data_pin[6]} {w_dac1_data_pin[7]} {w_dac1_data_pin[8]} {w_dac1_data_pin[9]} {w_dac1_data_pin[10]} {w_dac1_data_pin[11]} {w_dac1_data_pin[12]} {w_dac1_data_pin[13]} {w_dac1_data_pin[14]} {w_dac1_data_pin[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fcid_pulse_active_dac1]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 32 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {lan_endpoint_wrapper_inst/epB3pipe[0]} {lan_endpoint_wrapper_inst/epB3pipe[1]} {lan_endpoint_wrapper_inst/epB3pipe[2]} {lan_endpoint_wrapper_inst/epB3pipe[3]} {lan_endpoint_wrapper_inst/epB3pipe[4]} {lan_endpoint_wrapper_inst/epB3pipe[5]} {lan_endpoint_wrapper_inst/epB3pipe[6]} {lan_endpoint_wrapper_inst/epB3pipe[7]} {lan_endpoint_wrapper_inst/epB3pipe[8]} {lan_endpoint_wrapper_inst/epB3pipe[9]} {lan_endpoint_wrapper_inst/epB3pipe[10]} {lan_endpoint_wrapper_inst/epB3pipe[11]} {lan_endpoint_wrapper_inst/epB3pipe[12]} {lan_endpoint_wrapper_inst/epB3pipe[13]} {lan_endpoint_wrapper_inst/epB3pipe[14]} {lan_endpoint_wrapper_inst/epB3pipe[15]} {lan_endpoint_wrapper_inst/epB3pipe[16]} {lan_endpoint_wrapper_inst/epB3pipe[17]} {lan_endpoint_wrapper_inst/epB3pipe[18]} {lan_endpoint_wrapper_inst/epB3pipe[19]} {lan_endpoint_wrapper_inst/epB3pipe[20]} {lan_endpoint_wrapper_inst/epB3pipe[21]} {lan_endpoint_wrapper_inst/epB3pipe[22]} {lan_endpoint_wrapper_inst/epB3pipe[23]} {lan_endpoint_wrapper_inst/epB3pipe[24]} {lan_endpoint_wrapper_inst/epB3pipe[25]} {lan_endpoint_wrapper_inst/epB3pipe[26]} {lan_endpoint_wrapper_inst/epB3pipe[27]} {lan_endpoint_wrapper_inst/epB3pipe[28]} {lan_endpoint_wrapper_inst/epB3pipe[29]} {lan_endpoint_wrapper_inst/epB3pipe[30]} {lan_endpoint_wrapper_inst/epB3pipe[31]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 32 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {lan_endpoint_wrapper_inst/epBCpipe[0]} {lan_endpoint_wrapper_inst/epBCpipe[1]} {lan_endpoint_wrapper_inst/epBCpipe[2]} {lan_endpoint_wrapper_inst/epBCpipe[3]} {lan_endpoint_wrapper_inst/epBCpipe[4]} {lan_endpoint_wrapper_inst/epBCpipe[5]} {lan_endpoint_wrapper_inst/epBCpipe[6]} {lan_endpoint_wrapper_inst/epBCpipe[7]} {lan_endpoint_wrapper_inst/epBCpipe[8]} {lan_endpoint_wrapper_inst/epBCpipe[9]} {lan_endpoint_wrapper_inst/epBCpipe[10]} {lan_endpoint_wrapper_inst/epBCpipe[11]} {lan_endpoint_wrapper_inst/epBCpipe[12]} {lan_endpoint_wrapper_inst/epBCpipe[13]} {lan_endpoint_wrapper_inst/epBCpipe[14]} {lan_endpoint_wrapper_inst/epBCpipe[15]} {lan_endpoint_wrapper_inst/epBCpipe[16]} {lan_endpoint_wrapper_inst/epBCpipe[17]} {lan_endpoint_wrapper_inst/epBCpipe[18]} {lan_endpoint_wrapper_inst/epBCpipe[19]} {lan_endpoint_wrapper_inst/epBCpipe[20]} {lan_endpoint_wrapper_inst/epBCpipe[21]} {lan_endpoint_wrapper_inst/epBCpipe[22]} {lan_endpoint_wrapper_inst/epBCpipe[23]} {lan_endpoint_wrapper_inst/epBCpipe[24]} {lan_endpoint_wrapper_inst/epBCpipe[25]} {lan_endpoint_wrapper_inst/epBCpipe[26]} {lan_endpoint_wrapper_inst/epBCpipe[27]} {lan_endpoint_wrapper_inst/epBCpipe[28]} {lan_endpoint_wrapper_inst/epBCpipe[29]} {lan_endpoint_wrapper_inst/epBCpipe[30]} {lan_endpoint_wrapper_inst/epBCpipe[31]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 32 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {lan_endpoint_wrapper_inst/epBDpipe[0]} {lan_endpoint_wrapper_inst/epBDpipe[1]} {lan_endpoint_wrapper_inst/epBDpipe[2]} {lan_endpoint_wrapper_inst/epBDpipe[3]} {lan_endpoint_wrapper_inst/epBDpipe[4]} {lan_endpoint_wrapper_inst/epBDpipe[5]} {lan_endpoint_wrapper_inst/epBDpipe[6]} {lan_endpoint_wrapper_inst/epBDpipe[7]} {lan_endpoint_wrapper_inst/epBDpipe[8]} {lan_endpoint_wrapper_inst/epBDpipe[9]} {lan_endpoint_wrapper_inst/epBDpipe[10]} {lan_endpoint_wrapper_inst/epBDpipe[11]} {lan_endpoint_wrapper_inst/epBDpipe[12]} {lan_endpoint_wrapper_inst/epBDpipe[13]} {lan_endpoint_wrapper_inst/epBDpipe[14]} {lan_endpoint_wrapper_inst/epBDpipe[15]} {lan_endpoint_wrapper_inst/epBDpipe[16]} {lan_endpoint_wrapper_inst/epBDpipe[17]} {lan_endpoint_wrapper_inst/epBDpipe[18]} {lan_endpoint_wrapper_inst/epBDpipe[19]} {lan_endpoint_wrapper_inst/epBDpipe[20]} {lan_endpoint_wrapper_inst/epBDpipe[21]} {lan_endpoint_wrapper_inst/epBDpipe[22]} {lan_endpoint_wrapper_inst/epBDpipe[23]} {lan_endpoint_wrapper_inst/epBDpipe[24]} {lan_endpoint_wrapper_inst/epBDpipe[25]} {lan_endpoint_wrapper_inst/epBDpipe[26]} {lan_endpoint_wrapper_inst/epBDpipe[27]} {lan_endpoint_wrapper_inst/epBDpipe[28]} {lan_endpoint_wrapper_inst/epBDpipe[29]} {lan_endpoint_wrapper_inst/epBDpipe[30]} {lan_endpoint_wrapper_inst/epBDpipe[31]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list lan_endpoint_wrapper_inst/ep93wr]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list lan_endpoint_wrapper_inst/epB3rd]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list lan_endpoint_wrapper_inst/epBCrd]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
connect_debug_port u_ila_2/probe7 [get_nets [list lan_endpoint_wrapper_inst/epBDrd]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
set_property port_width 2 [get_debug_ports u_ila_3/probe1]
connect_debug_port u_ila_3/probe1 [get_nets [list {adc_wrapper__inst/control_hsadc_dual__inst/serdes[0].serdes_ddr_2lane_in_20bit_out_inst/i_data_s[0]} {adc_wrapper__inst/control_hsadc_dual__inst/serdes[0].serdes_ddr_2lane_in_20bit_out_inst/i_data_s[1]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe2]
set_property port_width 1 [get_debug_ports u_ila_3/probe2]
connect_debug_port u_ila_3/probe2 [get_nets [list adc_wrapper__inst/o_hsadc_pin_conv]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe3]
set_property port_width 1 [get_debug_ports u_ila_3/probe3]
connect_debug_port u_ila_3/probe3 [get_nets [list adc_wrapper__inst/o_hsadc_pin_sclk]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe1]
set_property port_width 32 [get_debug_ports u_ila_4/probe1]
connect_debug_port u_ila_4/probe1 [get_nets [list {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[0]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[1]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[2]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[3]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[4]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[5]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[6]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[7]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[8]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[9]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[10]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[11]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[12]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[13]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[14]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[15]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[16]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[17]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[18]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[19]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[20]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[21]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[22]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[23]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[24]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[25]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[26]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[27]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[28]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[29]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[30]} {slave_spi_mth_brd__M2_inst/o_port_pi_sadrs_h24C[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe2]
set_property port_width 32 [get_debug_ports u_ila_4/probe2]
connect_debug_port u_ila_4/probe2 [get_nets [list {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[0]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[1]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[2]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[3]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[4]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[5]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[6]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[7]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[8]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[9]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[10]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[11]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[12]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[13]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[14]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[15]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[16]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[17]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[18]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[19]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[20]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[21]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[22]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[23]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[24]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[25]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[26]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[27]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[28]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[29]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[30]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F4[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe3]
set_property port_width 32 [get_debug_ports u_ila_4/probe3]
connect_debug_port u_ila_4/probe3 [get_nets [list {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[0]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[1]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[2]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[3]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[4]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[5]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[6]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[7]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[8]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[9]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[10]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[11]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[12]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[13]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[14]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[15]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[16]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[17]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[18]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[19]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[20]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[21]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[22]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[23]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[24]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[25]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[26]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[27]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[28]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[29]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[30]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2F0[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe4]
set_property port_width 32 [get_debug_ports u_ila_4/probe4]
connect_debug_port u_ila_4/probe4 [get_nets [list {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[0]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[1]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[2]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[3]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[4]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[5]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[6]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[7]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[8]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[9]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[10]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[11]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[12]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[13]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[14]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[15]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[16]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[17]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[18]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[19]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[20]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[21]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[22]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[23]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[24]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[25]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[26]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[27]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[28]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[29]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[30]} {slave_spi_mth_brd__M2_inst/i_port_po_sadrs_h2CC[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe5]
set_property port_width 16 [get_debug_ports u_ila_4/probe5]
connect_debug_port u_ila_4/probe5 [get_nets [list {slave_spi_mth_brd__M2_inst/r_frame_mosi[0]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[1]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[2]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[3]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[4]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[5]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[6]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[7]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[8]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[9]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[10]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[11]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[12]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[13]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[14]} {slave_spi_mth_brd__M2_inst/r_frame_mosi[15]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe6]
set_property port_width 16 [get_debug_ports u_ila_4/probe6]
connect_debug_port u_ila_4/probe6 [get_nets [list {slave_spi_mth_brd__M2_inst/r_frame_miso[0]} {slave_spi_mth_brd__M2_inst/r_frame_miso[1]} {slave_spi_mth_brd__M2_inst/r_frame_miso[2]} {slave_spi_mth_brd__M2_inst/r_frame_miso[3]} {slave_spi_mth_brd__M2_inst/r_frame_miso[4]} {slave_spi_mth_brd__M2_inst/r_frame_miso[5]} {slave_spi_mth_brd__M2_inst/r_frame_miso[6]} {slave_spi_mth_brd__M2_inst/r_frame_miso[7]} {slave_spi_mth_brd__M2_inst/r_frame_miso[8]} {slave_spi_mth_brd__M2_inst/r_frame_miso[9]} {slave_spi_mth_brd__M2_inst/r_frame_miso[10]} {slave_spi_mth_brd__M2_inst/r_frame_miso[11]} {slave_spi_mth_brd__M2_inst/r_frame_miso[12]} {slave_spi_mth_brd__M2_inst/r_frame_miso[13]} {slave_spi_mth_brd__M2_inst/r_frame_miso[14]} {slave_spi_mth_brd__M2_inst/r_frame_miso[15]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe7]
set_property port_width 6 [get_debug_ports u_ila_4/probe7]
connect_debug_port u_ila_4/probe7 [get_nets [list {slave_spi_mth_brd__M2_inst/r_frame_ctrl[0]} {slave_spi_mth_brd__M2_inst/r_frame_ctrl[1]} {slave_spi_mth_brd__M2_inst/r_frame_ctrl[2]} {slave_spi_mth_brd__M2_inst/r_frame_ctrl[3]} {slave_spi_mth_brd__M2_inst/r_frame_ctrl[4]} {slave_spi_mth_brd__M2_inst/r_frame_ctrl[5]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe8]
set_property port_width 1 [get_debug_ports u_ila_4/probe8]
connect_debug_port u_ila_4/probe8 [get_nets [list slave_spi_mth_brd__M2_inst/i_SPI_CLK]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe9]
set_property port_width 1 [get_debug_ports u_ila_4/probe9]
connect_debug_port u_ila_4/probe9 [get_nets [list slave_spi_mth_brd__M2_inst/i_SPI_CS_B]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe10]
set_property port_width 1 [get_debug_ports u_ila_4/probe10]
connect_debug_port u_ila_4/probe10 [get_nets [list slave_spi_mth_brd__M2_inst/i_SPI_MOSI]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe11]
set_property port_width 1 [get_debug_ports u_ila_4/probe11]
connect_debug_port u_ila_4/probe11 [get_nets [list slave_spi_mth_brd__M2_inst/o_rd__sadrs_h2CC]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe12]
set_property port_width 1 [get_debug_ports u_ila_4/probe12]
connect_debug_port u_ila_4/probe12 [get_nets [list slave_spi_mth_brd__M2_inst/o_rd__sadrs_h2F0]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe13]
set_property port_width 1 [get_debug_ports u_ila_4/probe13]
connect_debug_port u_ila_4/probe13 [get_nets [list slave_spi_mth_brd__M2_inst/o_rd__sadrs_h2F4]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe14]
set_property port_width 1 [get_debug_ports u_ila_4/probe14]
connect_debug_port u_ila_4/probe14 [get_nets [list slave_spi_mth_brd__M2_inst/o_SPI_MISO]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe15]
set_property port_width 1 [get_debug_ports u_ila_4/probe15]
connect_debug_port u_ila_4/probe15 [get_nets [list slave_spi_mth_brd__M2_inst/o_SPI_MISO_EN]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe16]
set_property port_width 1 [get_debug_ports u_ila_4/probe16]
connect_debug_port u_ila_4/probe16 [get_nets [list slave_spi_mth_brd__M2_inst/o_wr__sadrs_h24C]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe17]
set_property port_width 1 [get_debug_ports u_ila_4/probe17]
connect_debug_port u_ila_4/probe17 [get_nets [list slave_spi_mth_brd__M2_inst/r_frame_miso_trig]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe1]
set_property port_width 18 [get_debug_ports u_ila_5/probe1]
connect_debug_port u_ila_5/probe1 [get_nets [list {adc_wrapper__inst/o_hsadc_fifo_adc1_din[0]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[1]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[2]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[3]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[4]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[5]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[6]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[7]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[8]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[9]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[10]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[11]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[12]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[13]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[14]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[15]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[16]} {adc_wrapper__inst/o_hsadc_fifo_adc1_din[17]}]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe2]
set_property port_width 1 [get_debug_ports u_ila_5/probe2]
connect_debug_port u_ila_5/probe2 [get_nets [list adc_wrapper__inst/i_hsadc_fifo_rst]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe3]
set_property port_width 1 [get_debug_ports u_ila_5/probe3]
connect_debug_port u_ila_5/probe3 [get_nets [list adc_wrapper__inst/o_hsadc_fifo_adc0_wr_ack]]
create_debug_port u_ila_5 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_5/probe4]
set_property port_width 1 [get_debug_ports u_ila_5/probe4]
connect_debug_port u_ila_5/probe4 [get_nets [list adc_wrapper__inst/o_hsadc_fifo_adc1_wr_ack]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets adc_fifo_clk]
