create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0_0_1_inst/inst/clk_out1_10M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sub_timestamp_inst/r_global_time_idx[0]} {sub_timestamp_inst/r_global_time_idx[1]} {sub_timestamp_inst/r_global_time_idx[2]} {sub_timestamp_inst/r_global_time_idx[3]} {sub_timestamp_inst/r_global_time_idx[4]} {sub_timestamp_inst/r_global_time_idx[5]} {sub_timestamp_inst/r_global_time_idx[6]} {sub_timestamp_inst/r_global_time_idx[7]} {sub_timestamp_inst/r_global_time_idx[8]} {sub_timestamp_inst/r_global_time_idx[9]} {sub_timestamp_inst/r_global_time_idx[10]} {sub_timestamp_inst/r_global_time_idx[11]} {sub_timestamp_inst/r_global_time_idx[12]} {sub_timestamp_inst/r_global_time_idx[13]} {sub_timestamp_inst/r_global_time_idx[14]} {sub_timestamp_inst/r_global_time_idx[15]} {sub_timestamp_inst/r_global_time_idx[16]} {sub_timestamp_inst/r_global_time_idx[17]} {sub_timestamp_inst/r_global_time_idx[18]} {sub_timestamp_inst/r_global_time_idx[19]} {sub_timestamp_inst/r_global_time_idx[20]} {sub_timestamp_inst/r_global_time_idx[21]} {sub_timestamp_inst/r_global_time_idx[22]} {sub_timestamp_inst/r_global_time_idx[23]} {sub_timestamp_inst/r_global_time_idx[24]} {sub_timestamp_inst/r_global_time_idx[25]} {sub_timestamp_inst/r_global_time_idx[26]} {sub_timestamp_inst/r_global_time_idx[27]} {sub_timestamp_inst/r_global_time_idx[28]} {sub_timestamp_inst/r_global_time_idx[29]} {sub_timestamp_inst/r_global_time_idx[30]} {sub_timestamp_inst/r_global_time_idx[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_2_2_inst/inst/clk_out1_104M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list FPGA_M0_SPI_TX_EN]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list w_M0_SPI_MISO]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list w_SSPI_TEST_done_frame]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list w_SSPI_TEST_MCLK]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list w_SSPI_TEST_MISO]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list w_SSPI_TEST_MISO_EN]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list w_SSPI_TEST_MOSI]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list w_SSPI_TEST_SCLK]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list w_SSPI_TEST_SS_B]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list w_SSPI_TEST_trig_frame]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list w_SSPI_TEST_trig_init]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets base_sspi_clk]
