##== TIME STAMP ==##
#set_property MARK_DEBUG true [get_nets {sub_timestamp_inst/r_global_time_idx[*]}]
set_property MARK_DEBUG true [get_nets {w_TIMESTAMP_WO[*]}]


##== TEMP SENSOR ==##
#
#set_property MARK_DEBUG true [get_nets r_temp_sig*]
#set_property MARK_DEBUG true [get_nets r_toggle_temp_sig*]


##== SPIO ==##
##set_property MARK_DEBUG true [get_nets SPIO0_CS]
##set_property MARK_DEBUG true [get_nets SPIO1_CS]
##set_property MARK_DEBUG true [get_nets SPIOx_MOSI]
##set_property MARK_DEBUG true [get_nets SPIOx_MISO]
##set_property MARK_DEBUG true [get_nets SPIOx_SCLK]
##set_property MARK_DEBUG true [get_nets {master_spi_mcp23s17_inst/state[*]}]
####set_property MARK_DEBUG true [get_nets {master_spi_mcp23s17_inst/r_fbit_index[*]}]
####set_property MARK_DEBUG true [get_nets {master_spi_mcp23s17_inst/r_shift_send_w32[*]}]
####set_property MARK_DEBUG true [get_nets {master_spi_mcp23s17_inst/r_shift_recv_w16[*]}]
####set_property MARK_DEBUG true [get_nets master_spi_mcp23s17_inst/r_R_W_bar]
##set_property MARK_DEBUG true [get_nets {master_spi_mcp23s17_inst/r_rd_DA[*]}]
##set_property MARK_DEBUG true [get_nets {master_spi_mcp23s17_inst/r_rd_DB[*]}]
##set_property MARK_DEBUG true [get_nets master_spi_mcp23s17_inst/r_trig_SPI_frame]
##set_property MARK_DEBUG true [get_nets master_spi_mcp23s17_inst/r_done_SPI_frame]
####set_property MARK_DEBUG true [get_nets master_spi_mcp23s17_inst/r_LNG_RSTn]
####set_property MARK_DEBUG true [get_nets master_spi_mcp23s17_inst/r_done_LNG_reset]


##== CLKD ==##
##set_property MARK_DEBUG true [get_nets CLKD_CS_B]
##set_property MARK_DEBUG true [get_nets CLKD_SCLK]
##set_property MARK_DEBUG true [get_nets CLKD_SDIO]
###set_property MARK_DEBUG true [get_nets CLKD_SDIO_rd]
##set_property MARK_DEBUG true [get_nets CLKD_SDO]
###set_property MARK_DEBUG true [get_nets CLKD_RST_B]
###set_property MARK_DEBUG true [get_nets CLKD_REFM]
###set_property MARK_DEBUG true [get_nets CLKD_LD]
###set_property MARK_DEBUG true [get_nets CLKD_STAT]
##set_property MARK_DEBUG true [get_nets {master_spi_ad9516_inst/state[*]}]
###set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/r_clken_div]
###set_property MARK_DEBUG true [get_nets {master_spi_ad9516_inst/r_fbit_index[*]}]
###set_property MARK_DEBUG true [get_nets {master_spi_ad9516_inst/r_shift_send_w24[*]}]
###set_property MARK_DEBUG true [get_nets {master_spi_ad9516_inst/r_shift_recv_w8[*]}]
###set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/r_R_W_bar]
##set_property MARK_DEBUG true [get_nets {master_spi_ad9516_inst/r_rd_D[*]}]
##set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/r_trig_SPI_frame]
##set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/r_done_SPI_frame]
###set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/i_trig_SPI_frame]
###set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/r_LNG_RSTn]
###set_property MARK_DEBUG true [get_nets master_spi_ad9516_inst/i_trig_LNG_reset]
###set_property MARK_DEBUG true [get_nets clk_dac_locked]
###set_property MARK_DEBUG true [get_nets w_CLKD_WO[*]]
###set_property MARK_DEBUG true [get_nets w_CLKD_WI[*]]
###set_property MARK_DEBUG true [get_nets w_CLKD_TI[*]]


##== DACX ==##
##set_property MARK_DEBUG true [get_nets DAC0_CS]
##set_property MARK_DEBUG true [get_nets DAC1_CS]
##set_property MARK_DEBUG true [get_nets DACx_SCLK]
##set_property MARK_DEBUG true [get_nets DACx_SDIO]
##set_property MARK_DEBUG true [get_nets DACx_SDO]
##set_property MARK_DEBUG true [get_nets DACx_RST_B]
##set_property MARK_DEBUG true [get_nets {master_spi_ad9783_inst/state[*]}]
####set_property MARK_DEBUG true [get_nets {master_spi_ad9783_inst/r_fbit_index[*]}]
####set_property MARK_DEBUG true [get_nets {master_spi_ad9783_inst/r_shift_send_w16[*]}]
####set_property MARK_DEBUG true [get_nets {master_spi_ad9783_inst/r_shift_recv_w8[*]}]
####set_property MARK_DEBUG true [get_nets master_spi_ad9783_inst/r_R_W_bar]
##set_property MARK_DEBUG true [get_nets {master_spi_ad9783_inst/r_rd_D[*]}]
##set_property MARK_DEBUG true [get_nets master_spi_ad9783_inst/r_trig_SPI_frame]
##set_property MARK_DEBUG true [get_nets master_spi_ad9783_inst/r_done_SPI_frame]
####set_property MARK_DEBUG true [get_nets master_spi_ad9783_inst/r_LNG_RSTn]
####set_property MARK_DEBUG true [get_nets dac0_dco_clk_locked]
####set_property MARK_DEBUG true [get_nets dac1_dco_clk_locked]


##== DAC Pattern Gen ==##
##  set_property MARK_DEBUG true [get_nets {DAC0_DAT[*]}]
##  set_property MARK_DEBUG true [get_nets {DAC1_DAT[*]}]

## CID test
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_cid_sq_pulse_run_dac0[*] ]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_cid_sq_pulse_run_dac1[*] ]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_cid_ff_pulse_run_dac0[*] ]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_cid_ff_pulse_run_dac1[*] ]
##  set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_cid_pulse_active_dac0  ]
##  set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_cid_pulse_active_dac1  ]
##  set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fcid_pulse_active_dac0 ]
##  set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fcid_pulse_active_dac1 ]
#
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/i_rstn_dac0_dco]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/i_rstn_dac1_dco]
#
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/o_dac0_active_dco]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/o_dac1_active_dco]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/o_dac0_active_clk]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/o_dac1_active_clk]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_dcs_active_dac0]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_dcs_active_dac1]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fdcs_active_dac0]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fdcs_active_dac1]
#
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dacx_data_seq_0[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dacx_data_seq_1[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dacx_data_seq_2[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dacx_data_seq_3[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dacx_adrs[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/i_trig_dacx_ctrl[*]}]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_mls_run]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dac0[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_mls_dac1[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_cnt_adrs_dac0[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_cnt_adrs_dac1[*]}]
##set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_wire_dacx_data[*]}]
#
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_run]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_dcs_run_dac0]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_dcs_run_dac1]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_dcs_rdy_dac0]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_dcs_rdy_dac1]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_data_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_data_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_repeat_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_repeat_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_cnt_duration_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_cnt_duration_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_cnt_adrs_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_cnt_adrs_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_cnt_repeat_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dcs_cnt_repeat_dac1[*]}]
#
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_run]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fdcs_run_dac0]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fdcs_run_dac1]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_active_dac0]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_active_dac1]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fdcs_rdy_dac0]
##set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/flag_fdcs_rdy_dac1]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_data_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_data_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_repeat_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_repeat_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_cnt_duration_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_cnt_duration_dac1[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_cnt_repeat_dac0[*]}]
#set_property MARK_DEBUG true [get_nets {dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_fdcs_cnt_repeat_dac1[*]}]
#
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac0_fifo_rd_en]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac0_fifo_empty]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac0_fifo_rst]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac0_fifo_reload1_rst]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac0_fifo_reload2_rst]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac1_fifo_rd_en]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac1_fifo_empty]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac1_fifo_rst]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac1_fifo_reload1_rst]
#set_property MARK_DEBUG true [get_nets dac_pattern_gen_wrapper__inst/dac_pattern_gen_inst/r_dac1_fifo_reload2_rst]
#
#set_property MARK_DEBUG true [get_nets {w_DAC0_DAT_PI[*]}]
#set_property MARK_DEBUG true [get_nets {w_DAC1_DAT_PI[*]}]
#set_property MARK_DEBUG true [get_nets w_DAC0_DAT_PI_WR]
#set_property MARK_DEBUG true [get_nets w_DAC1_DAT_PI_WR]


##== LAN ==##


##------------------------------------------------------------------------##

