# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -ruleid {1}  -id {DRC REQP-1839}  -suppress 
set_msg_config  -ruleid {10}  -id {DRC DPREG-4}  -suppress 
set_msg_config  -ruleid {11}  -id {DRC RTSTAT-10}  -suppress 
set_msg_config  -ruleid {12}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {13}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {14}  -id {Synth 8-295}  -new_severity {WARNING} 
set_msg_config  -ruleid {15}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {2}  -id {Common 17-1355}  -suppress 
set_msg_config  -ruleid {3}  -id {DRC CHECK-3}  -suppress 
set_msg_config  -ruleid {4}  -id {DRC DPIP-1}  -suppress 
set_msg_config  -ruleid {5}  -id {DRC REQP-1840}  -suppress 
set_msg_config  -ruleid {6}  -id {Synth 8-3332}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {Synth 8-3331}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {DRC DPOP-1}  -suppress 
set_msg_config  -ruleid {9}  -id {DRC DPOP-2}  -suppress 

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  open_checkpoint txem7310_pll__s3100_ms__top_routed.dcp
  set_property webtalk.parent_dir /media/sf_temp/dsn_s3100_ms_cpu_base_git/txem7310_pll__PGU_S3100/txem7310_pll.cache/wt [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files /media/sf_temp/dsn_s3100_ms_cpu_base_git/txem7310_pll__PGU_S3100/txem7310_pll.srcs/sources_1/ip/microblaze_mcs_1/bd_0/ip/ip_0/data/mb_bootloop_le.elf
  set_property SCOPED_TO_REF microblaze_mcs_1 [get_files -all /media/sf_temp/dsn_s3100_ms_cpu_base_git/txem7310_pll__PGU_S3100/txem7310_pll.srcs/sources_1/ip/microblaze_mcs_1/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
  set_property SCOPED_TO_CELLS inst/microblaze_I [get_files -all /media/sf_temp/dsn_s3100_ms_cpu_base_git/txem7310_pll__PGU_S3100/txem7310_pll.srcs/sources_1/ip/microblaze_mcs_1/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
  catch { write_mem_info -force txem7310_pll__s3100_ms__top.mmi }
  catch { write_bmm -force txem7310_pll__s3100_ms__top_bd.bmm }
  write_bitstream -force txem7310_pll__s3100_ms__top.bit 
  catch { write_sysdef -hwdef txem7310_pll__s3100_ms__top.hwdef -bitfile txem7310_pll__s3100_ms__top.bit -meminfo txem7310_pll__s3100_ms__top.mmi -file txem7310_pll__s3100_ms__top.sysdef }
  catch {write_debug_probes -quiet -force txem7310_pll__s3100_ms__top}
  catch {file copy -force txem7310_pll__s3100_ms__top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

